# Generated by Django 2.0.1 on 2018-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180130_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='annual_hours_of_operation',
            field=models.IntegerField(default=0),
        ),
    ]
