# Generated by Django 2.0.1 on 2018-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_sale_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('ballast', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('net_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('non_led_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='media/led_images/')),
                ('wattage', models.IntegerField(default=0)),
                ('conventional_wattage', models.IntegerField(default=0)),
                ('order_number', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('zero_to_fifty', models.CharField(default='0.00', max_length=254)),
                ('fifty_one_to_two_hundred', models.CharField(default='0.00', max_length=254)),
                ('two_hundred_one_to_five_hundred', models.CharField(default='0.00', max_length=254)),
                ('five_hundred_to_one_thousand', models.CharField(default='0.00', max_length=254)),
                ('min_visit_cost', models.CharField(default='0.00', max_length=254)),
                ('premium_ceiling_multiplier', models.CharField(default='0.00', max_length=254)),
                ('brands', models.CharField(blank=True, max_length=254, null=True)),
                ('colors', models.CharField(blank=True, max_length=254, null=True)),
                ('lumens', models.CharField(blank=True, max_length=254, null=True)),
                ('rated_average_life', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
