# Generated by Django 2.0.1 on 2018-01-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180131_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleled',
            old_name='delampingCount',
            new_name='delamping_count',
        ),
        migrations.RenameField(
            model_name='saleled',
            old_name='installationRequired',
            new_name='installation_required',
        ),
        migrations.RenameField(
            model_name='saleled',
            old_name='wattageReduction',
            new_name='wattage_reduction',
        ),
    ]
