# Generated by Django 2.0.1 on 2018-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180131_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('account_digits', models.IntegerField(default=12)),
                ('active', models.BooleanField(default=True)),
                ('zone_lookup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='utility',
            name='zones',
            field=models.ManyToManyField(to='webapp.Zone'),
        ),
    ]
