# Generated by Django 2.0.1 on 2018-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180131_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='zones',
            field=models.ManyToManyField(blank=True, to='webapp.Zone'),
        ),
    ]
