# Generated by Django 2.0.1 on 2018-02-01 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180131_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill_image',
            field=models.ImageField(blank=True, upload_to='media/bill_images/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='bill_type',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=7),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sale',
            name='kwh',
            field=models.IntegerField(default=0, verbose_name='kWh'),
        ),
        migrations.AddField(
            model_name='sale',
            name='month_of_bill',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.ServiceClass'),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='supply_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sale',
            name='supply_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='utility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Utility'),
        ),
        migrations.AddField(
            model_name='sale',
            name='utility_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='service_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
