# Generated by Django 2.0.1 on 2018-02-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20180202_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Zone'),
        ),
    ]
