# Generated by Django 2.0.1 on 2018-02-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_sale_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='utility_account_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
