# Generated by Django 2.0.1 on 2018-02-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20180202_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_usage_min', models.IntegerField(default=0)),
                ('annual_usage_max', models.IntegerField(default=100000)),
                ('sales_tax', models.DecimalField(decimal_places=5, max_digits=6)),
                ('marketing_adder', models.DecimalField(decimal_places=5, max_digits=6)),
                ('logistics_adder', models.DecimalField(decimal_places=5, max_digits=6)),
                ('energy_only_adder', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('term', models.IntegerField(default=24)),
                ('max_adder', models.DecimalField(decimal_places=5, default=0.05, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RetailEnergyProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('image', models.ImageField(upload_to='rep_logos/')),
                ('rate_upload', models.FileField(upload_to='rates/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='company',
        ),
        migrations.AlterField(
            model_name='led',
            name='image',
            field=models.ImageField(upload_to='led_images/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bill_image',
            field=models.ImageField(blank=True, upload_to='bill_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='agents',
            field=models.ManyToManyField(blank=True, to='webapp.Agent'),
        ),
        migrations.AddField(
            model_name='retailenergyprovider',
            name='teams',
            field=models.ManyToManyField(blank=True, to='webapp.Team'),
        ),
        migrations.AddField(
            model_name='rate',
            name='retail_energy_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.RetailEnergyProvider'),
        ),
        migrations.AddField(
            model_name='rate',
            name='service_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ServiceClass'),
        ),
        migrations.AddField(
            model_name='rate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Team'),
        ),
        migrations.AddField(
            model_name='rate',
            name='utility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Utility'),
        ),
        migrations.AddField(
            model_name='rate',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Zone'),
        ),
    ]
