# Generated by Django 2.0.1 on 2018-02-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20180203_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionscaler',
            name='service_class',
        ),
        migrations.RemoveField(
            model_name='consumptionscaler',
            name='utility',
        ),
        migrations.RemoveField(
            model_name='consumptionscaler',
            name='zone',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='supply_rate',
            new_name='base_rate',
        ),
        migrations.DeleteModel(
            name='ConsumptionScaler',
        ),
    ]
