# Generated by Django 2.0.1 on 2018-02-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20180203_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='retail_energy_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.RetailEnergyProvider'),
            preserve_default=False,
        ),
    ]
