# Generated by Django 2.0.1 on 2018-02-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_agent_retail_energy_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='agents',
        ),
        migrations.AddField(
            model_name='agent',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.Team'),
            preserve_default=False,
        ),
    ]
