# Generated by Django 2.0.1 on 2018-02-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20180204_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_installation_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='led',
            name='fifty_one_to_two_hundred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='led',
            name='five_hundred_to_one_thousand',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='led',
            name='min_visit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='led',
            name='premium_ceiling_multiplier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='led',
            name='two_hundred_one_to_five_hundred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='led',
            name='zero_to_fifty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
